#!/usr/bin/env ruby
# vim: set syntax=ruby

checks = {}
# Hash rockets
checks['=>'] = 'Quit using hash rockets' unless ENV['ALLOW_HASH_ROCKETS'] = 'true'

errors = []

files_changed = `git diff --cached --name-only`
files_changed.each_line do |filename|
  filename.chomp!
  file = open(filename)
  checks.each do |check, error_message|
    unless file.grep(/#{check}/).empty?
      errors << {key: check, file: filename}
    end
  end
end

unless errors.empty?
  errors.each do |error|
    puts "#{checks[error[:key]]}, '#{error[:key]}' found in #{error[:file]}"
  end
  exit 1
end
